/*****************************************************************************

		Copyright (c) 1984 - 1999 Prolog Development Center A/S

 Project:  DOCCNV
 FileName: RTF_PROC.H
 Purpose: RTF Parser. Token Processor
 Written by: Oleg V. Erjomin
 Comments:
******************************************************************************/

#ifndef __RTF_PROC_H__
#define __RTF_PROC_H__

BOOL process_Token (char *Text);

#endif
