/******************************************************************************

		Copyright (c) 1984 - 2000 Prolog Development Center A/S

 FileName:	CALC.PRO
 Purpose:	TRANSPORT OPTIMIZATION template file
 Written by:	Sergey Alexeev
 Comments:
******************************************************************************/
ifdef platform_16bit
  code = 5000
enddef

include "trans.inc"
include "calc.pre"

include "TOOLS\\CALC\\calc.pro"
