/******************************************************************************

		Copyright (c) 1984 - 2000 Prolog Development Center A/S

 FileName:	EDITFORM.PRO
 Purpose:	FORMS EDITOR template file
 Written by:	Andrew Skobelev
 Comments:	
******************************************************************************/
ifdef platform_16bit
  code = 5000
enddef

include "trans.inc"
include "tableed.pre"
include "editform.pre"
include "maphndl.pre"

include "TOOLS\\EDITFORM\\editform.pro"
