/******************************************************************************

		Copyright (c) 1984 - 2000 Prolog Development Center A/S

 FileName:	MAPHNDL.PRO
 Purpose:	Map viewer and editor for TRANS project.
 Written by:	Alexander Butovsky
 Comments:
******************************************************************************/
include "trans.inc"

include "mapctrl.pre"

include "editform.pre"
include "maphndl.pre"
include "tools\\maphndl\\maphndl.pro"
