/*****************************************************************************

		 Copyright (c) 1984 - 2000 Prolog Development Center A/S

 Project:  Easywin
 FileName: EASYWIN.INC
 Purpose:  Project's global declarations
 Written by: Alexander Gostintsev
 Comments:
*****************************************************************************/


/*****************************************************************************
			User's Declarations
*****************************************************************************/
