:userdoc.
:title.Fig and FigCap
:fig.
Area   Number  Classification         Code 
_______________________________________________
CDPG1
 
         5      Full-time exempt        1A
         1      Part-time exempt        1B
         3      Full-time non-exempt    2A
         1      Part-time non-exempt    2B
         1      Supplemental            3A
 
_______________________________________________
:figcap.Payroll Codes for Area CDPG1 
:efig.
:euserdoc. 
