// Generated by Selenium IDE,
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.nio.file.Paths;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddNewsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
            Paths.get("src/test/resources/chromedriver_win32/chromedriver.exe").toString());
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addNews() throws InterruptedException {
    driver.get("https://educats.by/login?returnUrl=%2Fweb%2Fdashboard");
    driver.manage().window().setSize(new Dimension(1477, 880));
    driver.findElement(By.id("mat-input-0")).sendKeys("testLecturer1");
    driver.findElement(By.id("mat-input-1")).sendKeys("testLecturer1");
    driver.findElement(By.cssSelector(".loginbtn > .mat-focus-indicator")).click();
    Thread.sleep(6000);
    driver.findElement(By.cssSelector("body > app-root > div > app-content-layout > app-nav > mat-toolbar.mat-toolbar.mat-elevation-z6.main-toolbar.first.mat-primary.mat-toolbar-single-row > div:nth-child(3) > a"))
            .click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("body > app-root > div > app-content-layout > app-subjects-nav > mat-toolbar > button")).click();
    Thread.sleep(6500);
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".mat-raised-button > .mat-button-wrapper")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".mat-row:nth-child(5) .navigation-link")).click();
    Thread.sleep(6500);
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-raised-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().frame(0);
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-primary > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".mat-primary > .mat-button-wrapper")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("mat-input-0")).click();
    driver.findElement(By.id("mat-input-0")).sendKeys("test");
    driver.findElement(By.cssSelector("#mat-dialog-0 > app-news-popover > app-popover > div > div > div.mat-dialog-actions > button.mat-raised-button.mat-primary")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 2);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".subject-news-component__news-title")));
    }
  }
}
