// Generated by Selenium IDE,

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class CheckAboutTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver",
                Paths.get("src/test/resources/chromedriver_win32/chromedriver.exe").toString());
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void checkAbout() throws InterruptedException {
        driver.get("https://educats.by/login?returnUrl=%2Fweb%2Fdashboard");
        driver.manage().window().setSize(new Dimension(1477, 880));
        driver.findElement(By.id("mat-input-0")).sendKeys("testLecturer1");
        driver.findElement(By.id("mat-input-1")).sendKeys("testLecturer1");
        driver.findElement(By.cssSelector(".loginbtn > .mat-focus-indicator")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector("body > app-root > div > app-content-layout > app-nav > mat-toolbar.mat-toolbar.mat-elevation-z6.main-toolbar.first.mat-primary.mat-toolbar-single-row > button.mat-focus-indicator.mat-menu-trigger.icon-h.mat-icon-button.mat-button-base")).click();
        driver.findElement(By.cssSelector("#mat-menu-panel-0 > div > button:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector(".first")).getText(), is("Educats - это"));
    }
}
