// Generated by Selenium IDE,
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.nio.file.Paths;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
            Paths.get("src/test/resources/chromedriver_win32/chromedriver.exe").toString());
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() throws InterruptedException {
    driver.get("https://educats.by/login?returnUrl=%2Fweb%2Fdashboard");
    driver.manage().window().setSize(new Dimension(1477, 880));
    driver.findElement(By.id("mat-input-0")).sendKeys("testLecturer1");
    driver.findElement(By.id("mat-input-1")).sendKeys("testLecturer1");
    driver.findElement(By.cssSelector(".loginbtn > .mat-focus-indicator")).click();
    Thread.sleep(6000);
    {
      WebDriverWait wait = new WebDriverWait(driver, 8);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("mat-input-2")));
    }
  }
}
