// Generated by Selenium IDE,

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.nio.file.Paths;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UpdateSubjectSpaceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
            Paths.get("src/test/resources/chromedriver_win32/chromedriver.exe").toString());
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void updateSubjectSpace() throws InterruptedException {
    driver.get("https://educats.by/login?returnUrl=%2Fweb%2Fdashboard");
    driver.manage().window().setSize(new Dimension(1477, 880));
    driver.findElement(By.id("mat-input-0")).sendKeys("testLecturer1");
    driver.findElement(By.id("mat-input-1")).sendKeys("testLecturer1");
    driver.findElement(By.cssSelector(".loginbtn > .mat-focus-indicator")).click();
    Thread.sleep(6000);
    driver.findElement(By.cssSelector("body > app-root > div > app-content-layout > app-nav > mat-toolbar.mat-toolbar.mat-elevation-z6.main-toolbar.first.mat-primary.mat-toolbar-single-row > div:nth-child(3) > a"))
            .click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector("body > app-root > div > app-content-layout > app-subjects-nav > mat-toolbar > button")).click();
    Thread.sleep(6500);

    driver.switchTo().frame(0);
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-row:nth-child(7) .mat-icon-button:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-row:nth-child(7) .mat-icon-button:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-row:nth-child(8) .mat-icon-button:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-row:nth-child(9) .mat-icon-button:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("body > app-root > div > div > app-subject > div > table > tbody > tr:nth-child(9) > td.mat-cell.cdk-column-actions.mat-column-actions > button:nth-child(2)")).click();
    Thread.sleep(3000);
    driver.findElement(By.id("mat-input-1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-raised-button:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("mat-input-1")).sendKeys("updated");
    driver.findElement(By.cssSelector("#mat-dialog-0 > app-news-popover > div > div.mat-dialog-actions > button.mat-raised-button.mat-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-row:nth-child(2) .mat-icon-button:nth-child(2) .mat-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".mat-row:nth-child(9) > .cdk-column-shortName"));
      assert (elements.size() > 0);
    }
  }
}
