/*****************************************************************************

		Copyright (c) 1984 - 1999 Prolog Development Center A/S

 Project:  DOCCNV
 FileName: RTF_FOOT.H
 Purpose: RTF Parser. Footnotes handling
 Written by: Oleg V. Erjomin
 Comments:
******************************************************************************/

#ifndef __RTF_FOOT_H__
#define __RTF_FOOT_H__

BOOL get_Foot_Code (void);
void ClearFootNote (void);
void MakePageAttributies (void);

#endif
