/*****************************************************************************

		Copyright (c) 1984 - 1999 Prolog Development Center A/S

 Project:  DOCCNV
 FileName: RTF_STMT.C
 Purpose: RTF Parser. Statement handling
 Written by: Oleg V. Erjomin
 Comments:
******************************************************************************/

#ifndef __RTF_STMT_H__
#define __RTF_STMT_H__

void stmt_Begin (void);
void stmt_End (void);

#endif
