/*****************************************************************************

		Copyright (c) 1984 - 2000 Prolog Development Center A/S

 Project:  simple1
 FileName: SIMPLE1.INC
 Purpose:  Project's global declarations
 Written by: Visual Prolog
 Comments:
*****************************************************************************/


/*****************************************************************************
			User's Declarations
*****************************************************************************/
