/*****************************************************************************

		Copyright (c) 1984 - 2000 Prolog Development Center A/S

 Project:  simple2
 FileName: SIMPLE2.INC
 Purpose:  Project's global declarations
 Written by: Visual Prolog
 Comments:
*****************************************************************************/


/*****************************************************************************
			User's Declarations
*****************************************************************************/
