/*****************************************************************************

		Copyright (c) 1984 - 2000 Prolog Development Center A/S

 Project:  CGI Examples
 FileName: CGIEXAM.INC
 Purpose: Common Includes for CGI Examples
 Written by: Oleg V. Erjomin
 Comments:
******************************************************************************/

/*****************************************************************************
			User's Declarations
*****************************************************************************/

include "types.dom"		
include "pdcrunt.dom"		
include "cgitools.dom"

include "pdcrunt.pre"
include "cgitools.pre"